[project]
name = "adult-income-analysis"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kagglehub>=0.2.9",
    "seaborn>=0.13.2",
]
